package it.polimi.ingsw.model;

/**
 * Possible player state during his turn.
 */
public enum PlayerState {
    LEADER_MANAGE_BEFORE,

    //MARKET
    WHITE_MARBLE_CONVERSION,
    MARKET_RESOURCE_POSITIONING,

    //BUY DEVELOPMENT
    ANY_BUY_DEV_CONVERSION,
    BUY_DEV_RESOURCE_REMOVING,

    //PRODUCTION
    PRODUCTION_ACTION,
    ANY_PRODUCE_COST_CONVERSION,
    ANY_PRODUCE_PROFIT_CONVERSION,
    PRODUCTION_RESOURCE_REMOVING,

    //END
    LEADER_MANAGE_AFTER
}
