package it.polimi.ingsw.controller;

/**
 * Class State is an enumeration
 */
public enum TurnState {
    LEADER_MANAGE_BEFORE,

    //MARKET
    WHITE_MARBLE_CONVERSION,
    MARKET_RESOURCE_POSITIONING,

    //BUY DEVELOPMENT
    ANY_BUY_DEV_CONVERSION,
    BUY_DEV_RESOURCE_REMOVING,

    //PRODUCTION
    PRODUCTION_ACTION,
    ANY_PRODUCE_COST_CONVERSION,
    ANY_PRODUCE_PROFIT_CONVERSION,
    PRODUCTION_RESOURCE_REMOVING,

    //END
    LEADER_MANAGE_AFTER,


    //NOT USED
    MARKET_ACTION,
    BUY_DEVELOPMENT_ACTION


}
